In [1]:
# 1. What is a Python library? Why do we use Python libraries?

In [ ]:
A Python library is a collection of pre-written code that provides functionality for various tasks.
We use python libraries for Code Reusability, Efficiency and Productivity & Time saving.

In [ ]:
#2. What is the difference between Numpy array and List?

In [ ]:
Numpy array are faster and have restrictions of having homogeneity of the objects while lists can have multiple type of data.

In [ ]:
#3. Find the shape, size and dimension of the following array?

In [ ]:
[[1,2,3,4]
[5,6,7,8]
[9,10,11,12]]

In [4]:
import numpy as np

In [7]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [10]:
A.shape # Shape

(3, 4)

In [11]:
A.size  # Size

12

In [12]:
A.ndim  # Dimension

2

In [ ]:
#4. Write python code to access the first row of the following array?

In [14]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [23]:
A[0]  ## First Row

array([1, 2, 3, 4])

In [29]:
#5. How do you access the element at the third row and fourth column from the given numpy array?

In [25]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [28]:
A[2,3] ## 3rd Row & 4th Column Element

12

In [30]:
#6.Write code to extract all odd-indexed elements from the given numpy array?

In [7]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

odd_indexed_elements = array[1::2, 1::2]

print("Original array:")
print(array)
print("\nOdd-indexed elements:")
print(odd_indexed_elements)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Odd-indexed elements:
[[6 8]]


In [9]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [10]:
random_matrix=np.random.rand(3,3)

In [12]:
random_matrix

array([[0.27099783, 0.10418987, 0.60485532],
       [0.76377797, 0.81886364, 0.65030463],
       [0.44430579, 0.20492774, 0.0653465 ]])

In [13]:
#8.Describe the difference between np.random.rand and np.random.randn?

In [14]:
#9.Write code to increase the dimension of the following array?

In [33]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [34]:
increased_dim_3 = A[np.newaxis, :]
increased_dim_4 = A[: , np.newaxis]

In [36]:
increased_dim_1 = np.expand_dims(array, axis=0)
increased_dim_2 = np.expand_dims(array, axis=1) 

In [38]:
increased_dim_2

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [39]:
#10.How to transpose the following array in NumPy?

In [40]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [41]:
A_transpose=np.transpose(A)

In [42]:
A_transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
#11.Consider the following matrix:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
#Index wise multiplication

In [56]:
index_multiply=A*B

In [57]:
index_multiply

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [52]:
##Matrix Multiplication

In [58]:
matrix_multiply=A @ B

In [59]:
matrix_multiply

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [60]:
##Add both the matrics

In [61]:
add_matrics=A+B

In [62]:
add_matrics

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [63]:
##Subtract matrix B from A 

In [64]:
subtract_matrix=B-A

In [65]:
subtract_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [66]:
##Divide Matrix B by A

In [67]:
divide_matrix=B/A

In [68]:
divide_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
##12.Which function in Numpy can be used to swap the byte order of an array?

In [ ]:
np.ndarray.byteswap()

In [70]:
#13. What is the significance of the np.linalg.inv function?

In [72]:
#14.What does the np.reshape function do, and how is it used?

In [73]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
reshaped_array = np.reshape(array, (2, 4))

In [75]:
reshaped_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
#15.What is broadcasting in Numpy?

In [77]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=10

In [78]:
result=A+B

In [80]:
result

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])